### ISSUE TITLE
randomNames(0) returns more than 'n' random first and/or last names.

### ISSUE THREAD

**Issue by mlrus** [CenterForAssessment/randomNames#15]
The documentation states that the argument of```randomNames(n)``` indicates "how many names to produce".   In fact, the method always returns at least one name, which is contrary to the stated documentation.  This affects correctness of the following examples
```R
names <- append(names, randomNames::randomNames(num - length(names)))
```
```R
test_that("test number of generated names", {
  expect_equal(10, length(randomNames(10)))
  expect_equal(1,  length(randomNames(1)))
  expect_equal(0,  length(randomNames(0)))
})
```

As of **randomNames 0.1-0.0**, the documentation says 
```text
       n: OPTIONAL. Integer indicating how many name to produce. Best
          to use when no gender or ethnicity data is provided and one
          simple wants ‘n’ random first and/or last names.
```

**Comment by dbetebenner** [comment]
Sorry for letting this one lag. I could change the documentation to say POSITIVE integer to close that loophole. I also added in a check so that randomNames needs a positive integer otherwise it returns NULL (and passes the test you propose). Let me know if that behavior doesn't suit your needs
