### ISSUE TITLE
firstnames weighted by birth year?

### ISSUE THREAD

**Issue by higgi13425** [CenterForAssessment/randomNames#66]
Hi - this is a neat package for a specific purpose.  One possible nice feature - could you set parameters birth_year_start = 1960 (default) and birth_year_end = 2000 (default), The user could then change these parameters to get firstnames appropriate for people born between 1880-1890, or 2000-2010. Ideally this would use the weighted frequency of each firstname by gender for the included range of birth years.

**Comment by dbetebenner** [comment]
Hi. Sorry for the delay on replying. Unfortunately, I don't have any information in the data set that's being used to generate the names on which names go with which years.
