### ISSUE TITLE
Error message populating out even though the package runs fine

### ISSUE THREAD

**Issue by debbie1996** [CenterForAssessment/randomNames#67]
Installing the package and importing into the library statements for randomNames package is fine, but during the import statement library(randomNames) there will always be an error message populating:
randomNames 1.4-0.0  (3-7-2019). For help: >help("randomNames") or visit https://centerforassessment.github.io/randomNames
![error msg](https://user-images.githubusercontent.com/36845895/59648519-e80e4900-91b1-11e9-9406-8da89739a490.PNG)

**Comment by dbetebenner** [comment]
Thanks for posting the info. I don't get that when I load the package, could you give me your `sessionInfo()` and I'll try to figure out why you're getting that message.

**Comment by debbie1996** [comment]
Hi Damian,


Thank you for the reply. This is what I get when sessionInfo() is ran:

R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=English_Singapore.1252  LC_CTYPE=English_Singapore.1252
[3] LC_MONETARY=English_Singapore.1252 LC_NUMERIC=C
[5] LC_TIME=English_Singapore.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0



Many thanks, and happy Friday!



Warmest regards,
Debbie Lee
Singapore Management University School of Information Systems
+6598630869<tel:+6598630869> | debbie.lee.2016@sis.smu.edu.sg<mailto:debbie.lee.2016@sis.smu.edu.sg>


________________________________

**Comment by dbetebenner** [comment]
Hmmm. Not sure what's up. Tried about everything to reproduce (Windows, RStudio, new R version, older version of data.table). 

Could you show your `sessionInfo()` after loading the `randomNames` package. 

```
library(randomNames)
sessionInfo()
```
