### ISSUE TITLE
Leading whitespaces in some names

### ISSUE THREAD

**Issue by Close-your-eyes** [CenterForAssessment/randomNames#70]
When running the command
`randomNames(1, which.names = "first", gender = 1)`
some names are returned which have leading whitespaces. E.g. " Huda" and " Muzna".

Even though this can be fixed easily with trimws it is unexpected and maybe problematic to some people if these names are also returned without whitespace sometimes.

**Comment by dbetebenner** [comment]
Thanks for finding that. I'll fix those up in the data and repost to GitHub and CRAN in the next few days.

**Comment by dbetebenner** [comment]
Just fixed that and built v 1.5 of randomName. Will post to CRAN shortly
